### ISSUE TITLE
Student Q&A Request

### ISSUE THREAD

**Issue by RyanOttignon** [TimPaterson/CNC-Tool-Library-Manager#1]
Hi Tim,

I know this is probably not in the right spot, but I have found no other way to contact you after your previous site shut down. My name is Ryan and I'm a high school student from New Jersey. We have been given an assignment to create a biography of a person we look up to and analyze one of their main works, and I chose you, the father of DOS.
While researching, I fell pretty deep into the 86-DOS rabbithole and found a lot of questions unanswered, ones that are important to the timeline of 86-DOS development. If you have time, are you able to answer these questions?

1. Were any versions between 0.34 and 1.00 (0.42 - 0.80) ever released?
2. Did a version just named "0.3" (not 0.33 or 0.34) exist?
3. I've heard you kept directory listings from early versions of 86-DOS - is this true, and are they available to share?
4. Are there any other versions before 0.3/0.33 besides the 0.10, 0.11, and 0.20? (On another note, is 0.20 the correct version number for the version where EDLIN was added?)

If you want, you can contact me via my school email: `s101885 AT outlook DOT com` (replacing AT with @ and DOT with .)
You can also just comment here.

Thank you so much for you amazing work on this operating system - you're truly a pioneer, creating and improving so many of the concepts the world depends on today - and thanks for you time!

Sincerely,
Ryan Ottignon

**Comment by TimPaterson** [comment]
Well, we're relying on my memory from 40+ years ago, and that's not good. The short answer is I can't help much with any of your questions.

1. I assume you've seen the version history in the source code and are asking about the versions listed there (0.42, 0.56, 0.60, etc.). Those numbers would represent the point when the described feature was stable. (For example, it would be fair to say it took a number of tries to get 0.56 "Variable record and sector sizes" working.) As such, I would assume that each one listed would have been become the current shipped version. However, SCP had very limited sales of the 8086 computer system in the early days, so it's possible there were no shipments between some versions.

2. So a version 0.3 must have existed, but I can't tell you if it was considered stable or ever shipped. All 0.3x would have the same feature level and therefore the same manual. The hundredths digit distinguished bug fixes and would not be referenced in documentation.

3. Sorry, no directory listings.

4. I don't remember about other versions. You (and Wikipedia) mention 0.2, but I haven't found any other references to it and don't know what's different about it.

**Comment by RyanOttignon** [comment]
Tim,

Thank you for the quick reply! The information you've shared is extremely valuable to my research, and it will definitely be used.
For your 4th answer - a preliminary instruction manual that you released from ca. October 1980 seems to be from a version between 0.11 (as described in _The Roots of DOS: Tim Paterson_ by David Hunter) and version 0.3 (as seen in the "Version 0.3" User's and Programmer's manuals you put out on your old website). If you want to take a quick look over, I'll take any information you remember!
Once again, thank you for your response! (Feel free to close this issue if you have nothing else to share)

Ryan Ottignon

**Comment by RyanOttignon** [comment]
Tim, I apologize for the reopening of this, but my curiosity has gotten the best of me. The following questions sprout from various sources - court documents, email interviews, Usenet messages, BBS posts, etc.

1. Do you know who Joseph/Joe Boykin is? He claims to be a former consultant of Seattle Computer Products  and says that he's "one of three authors" of 86-DOS. (On that note, is the three authors quote true?)
2. Did you ever interact with Richard Lomas? He owned Lomas Data Products and Rod Brock struck a deal with him to sell 86-DOS with the LDP88 computer.
3. Who is Patrick/Pat Opalka? Did he work on 86-DOS?
4. Do you remember if 86-DOS was licensed to or sold by any other companies besides Microsoft and Lomas Data Products? I've heard the number of licensers be as high as a dozen.
5. Do you remember the 1985 Pacific Coast Computer Fair? You apparently spoke at it, and I can't find any other information about it.
6. Do you still have your memoir _The Right Place... The Right Time_? Do you have any plans to publish it?

Thank you for your time!

Ryan Ottignon

**Comment by TimPaterson** [comment]
Pat Opalka Is a brilliant EE who was 1 or 2 years behind me at UW.  I met him when he was hired as another technician at Retail Computer Store.  When he graduated I encouraged SCP to hire him as their second full-time engineer.  He came with me when I started Falcon Technology (1983).

I was the only one to work on DOS before MSFT bought it.  Exception:  After I left SCP for MSFT (May 1980), Pat (at SCP) found and fixed a bug (1.01 dated 5/12/81), forwarding the fix to me at MSFT.  But there were not "three authors".

Where did you hear about my "memoir"?

Any of your questions I have not addressed means I have no recollection (e.g., I don't recall a Joe Boykin).

**Comment by RyanOttignon** [comment]
Thank you for the information!

> But there were not "three authors".

Interesting! (Here are the original comments made by this Joe Boykin: [one Usenet comment](https://groups.google.com/g/alt.folklore.computers/c/naOF8R0R0TU/m/7WBhOGD7MHsJ) and [his website](https://www.theboykins.com/family.html))

> Where did you hear about my "memoir"?

Court documents, specifically your interview from your lawsuit in 2007. The document is sealed (for good reason!) so I have to rely on the snippets talked about in your interview, which is incomplete.

On the other questions that you have to recollection of:
2. This makes sense. Richard told me that he talked with Rod Brock and they worked on a deal (not a real license, just a verbal agreement) to sell 86-DOS at a discounted rate.
6. Here's the original message:
_"Tim Patterson who wrote 86-DOS did some custom contract programming for me at GTE around the same timeframe."_
I asked what GTE was and asked if the work was between February 1980 and April 1981 and he replied:
_"GTE was the largest telephone company in the US that was not part of the original Bell System. They merged with Bell Atlantic to become Verizon. Yes, it was during that timeframe. Tim wrote some custom memory board test software that was used to faulty diagnose memory boards used in telephone switching systems.
At this time I was the Equipment Service Center on Adamo Drive. These memory boards were used in the Automatic Electric GTD-1000 PABX and GTD-4600 CENTREX. At that time we didn’t repair any of the GTD-5 boards."_

I have two more questions that have been bugging me for a bit.

1. You said that 1.01 was a bug fix by Pat Opalka. Versions 1.10 (but not 1.11, 1.12, or 1.13) are often listed as 86-DOS versions. However, this doesn't seem to make sense to me. Were they ever sent to SCP or were they a purely Microsoft thing?
2. An 86-DOS version 1.14 disk was imaged by Rich Cini in 2017, but you seem to have been working at Microsoft. Did you help out on this? Was it an early OEM release of MS-DOS?

Ryan Ottignon

**Comment by TimPaterson** [comment]
Microsoft didn't have any customers for DOS besides IBM until 1.25. So any release with a lower version is 86-DOS. I think SCP was kept current with changes I was making at MSFT. (I went back to SCP upon completion of 1.25, April 1982.)

The only DOS source code I have is 1.25, now here on [GitHub](https://github.com/microsoft/ms-dos).

**Comment by RyanOttignon** [comment]
> Microsoft didn't have any customers for DOS besides IBM until 1.25.
Just want to confirm this - from what I've heard, it's generally accepted that MS-DOS 1.24 was the basis for PC-DOS 1.1. Is this correct?

Also, [IO.ASM](https://github.com/microsoft/MS-DOS/blob/master/v1.25/source/IO.ASM) from the 1.25 source code you shared mentions "MS-DOS 1.20". Would it be safe to assume the following?
- You under Seattle Computer Products solely made all versions up to **86-DOS** 1.00.
- Pat Opalka under Seattle Computer Products found a bug and fixed it, creating **86-DOS** 1.01. This was sent to you at Microsoft.
- You under Microsoft made various changes to **86-DOS** 1.01. This version was called **MS-DOS** 1.10.
- Each change made including and after MS-DOS 1.10 was sent back to Seattle Computer Products, who sold it under the 86-DOS name. For example, the change labelled MS-DOS 1.14 was sent back to Seattle Computer Products, who called it 86-DOS 1.14.
- When MS-DOS 1.25 was released to the general public, SCP dropped the "86-DOS" name and called it an MS-DOS OEM.

Ryan Ottignon

**Comment by RyanOttignon** [comment]
I've been holding off on this because I don't want to nag you in a GitHub issue for 40-year-old information, but I contacted so many people and I've gotten a few more questions as a result.

First, what I've done already.

I contacted Pat Opalka, who I mentioned in another comment here, and he was happy to scan and archive what he had. He was able to send over PDF copies of ten hardware and software manuals, as well as disk images of five 5.25" North Star floppies containing 86-DOS versions 1.10 and 1.14, plus SCP's OEM of MS-DOS 1.25.

I also contacted a few Microsoft and IBM alum. I've reached Bob O'Rear (MS) and Lew Eggebrecht (IBM) already, and I hope to reach others such as Pat Harrington and Lou Flashinski (both IBM). Bob sent over 14 scans of his notes, letters, and memos from the time. Lew sent over what he remembered from the time and our conversation is still ongoing.

Finally, I last talked to Robert Brock, son of Rod Brock. He actually contacted me after his nephew found a request of mine online. He said he might have software, source code, manuals, pictures, etc. from the time but it might take a while to dig it up.

Second, my business. I have three questions based on prior conversations and findings.

1: In Gates by Stephen Manes and Paul Andrews, they reference a letter between you and Bob O'Rear on August 5, 1980. You apparently asked if Bob was able to adapt BASIC for your new OS. Bob doesn't have the letter still, nor do either of the authors of the book. Do you happen to still have it? (Any other letters of interest would be great too, but this one is especially important.)

2: Bill Machrone reviewed SCP's 8086 system in late 1981, along with 86-DOS. He mentioned that it took a while for BASIC to be translated for 86-DOS. It was apparently done by Microsoft with your help - Bob O'Rear couldn't remember if he did this or not. Can you recall when this translation was done?

3: Pat Opalka's 5.25" North Star disks contained a file called "WM.COM", as well as a "WMCONFIG.ASM" file and a note describing what it is. It was called "SCP Super Editor", version 1.00, and it was made by you. It says it is like MicroPro Word Master, which I believe you used at the time. Can you give any more details into what this is and when you made it/what version you made it for?

That's all I have. Thanks once again for your time and I apologize again for the weird method of contact.

**Comment by TimPaterson** [comment]
1. Don't remember a letter, don't have a copy.
2. BASIC conversion to DOS would have been part of the Microsoft-IBM deal.  I wasn't part of that.
3. WM was MicroPro WordMaster for CP/M, disassembled into Z80 source code that could be assembled again, then run through the Z80-to-8086 translator so it would run on DOS. I didn't write it and we didn't distribute it.

**Comment by Rhinozz** [comment]
I'll talk to Bob about #2 (you can take a look at the documents [here](https://archive.org/details/orear-collection/) if you're interested). About #3 - can you give an approximate date (relative or absolute, doesn't matter) you decompiled/translated it?

One more question I forgot to ask. While looking through some of the manuals you published on your old site, I found the MON-86 version 1.4 manual. The last few pages contain an assembly listing of the source code and include a date of February 18, 1980.

This date lines up conveniently with the other early-February date around the time, when you got permission from Rod to write the operating system. I also found that you first created a debugger in ROM to aid with the development of 86-DOS - please correct this if I'm wrong. And finally, you've said that the debugger was originally a part of the 8086 monitor, once again lining up nicely.

The issue is that I don't have version 1.3 of MON-86, nor its manual, and version 1.5 came out shortly after (April 24, 1980). As far as I can tell, 1.5 didn't add anything major like a new instruction, but I'm unable to verify with the prior version.

So, my question: are you able to recall if version 1.4 of MON-86 was made in preparation for 86-DOS, or if it was the one that introduced debugging capabilities? And do you remember anything other that you did to prepare for development in February, March, and early April?

**Comment by RyanOttignon** [comment]
Talked to Bob about #2 - he was unfortunately able to remember. Sad. (Side note: you can take a look at the notes he sent me [here](https://archive.org/details/orear-collection/) if you're interested.) About #3 - can you give an approximate date (relative or absolute, doesn't matter) you decompiled/translated it?

One more question I forgot to ask. While looking through some of the manuals you published on your old site, I found the MON-86 version 1.4 manual. The last few pages contain an assembly listing of the source code and include a date of February 18, 1980.

This date lines up conveniently with the other early-February date around the time, when you got permission from Rod to write the operating system. I also found that you first created a debugger in ROM to aid with the development of 86-DOS - please correct this if I'm wrong. And finally, you've said that the debugger was originally a part of the 8086 monitor, once again lining up nicely.

The issue is that I don't have version 1.3 of MON-86, nor its manual, and version 1.5 came out shortly after (April 24, 1980). As far as I can tell, 1.5 didn't add anything major like a new instruction, but I'm unable to verify with the prior version.

So, my question: are you able to recall if version 1.4 of MON-86 was made in preparation for 86-DOS, or if it was the one that introduced debugging capabilities? And do you remember anything other that you did to prepare for development in February, March, and early April?

Thanks once more.
