### ISSUE TITLE
Does this work with LibreOffice as well?

### ISSUE THREAD

**Issue by Quas7** [TimPaterson/CNC-Tool-Library-Manager#4]
Hi,

I stumpled over the "no more TSV export" in Fusion360 (workaround will stop working 6th Sep. 2022) and I need this to work with G-Wizard. Google quickly pointed me here.

I tried to run the VBA via LibreOffice Calc but failed (with macro security set to zero).
I just wondered, if it would be a big effort to get this nice tool compatible to nudge it even more into the open source domain. ;)

Cheers.

**Comment by TimPaterson** [comment]
I dunno, never heard of it.
